export class Team{
  id : number = 0
  players : number[] = []
  teamName : string = ""
  teamType : string = ""

  teamPlayed : number = 0
  homePlayed : number = 0
  visitPlayed : number = 0

  teamImageUrl : string = ""

  teamGoals : number = 0;
  homeGoals : number = 0;
  visitGoals : number = 0;

  teamLoss : number = 0;
  homeLoss : number = 0
  visitLoss : number = 0

  teamPoints : number = 0;
  homePoints : number = 0
  visitPoints : number = 0

  teamWin : number = 0;
  homeWin : number = 0;
  visitWin : number = 0;

  teamLose : number = 0;
  homeLose : number = 0;
  visitLose : number = 0;

  teamDraw : number = 0;
  homeDraw : number = 0;
  visitDraw : number = 0;

  teamSupport : number = 0;
  teamSteal : number = 0;
  teamFoul : number = 0;
  teamYellow : number = 0;
  Team(){

  }
}